import Navigation from "@/components/navigation/Navigation";
import StatusBar from "@/components/header/StatusBar";
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Breadscrumbs from "@/components/breadcrumbs/Breadcrumbs";
import Core from "@/components/core/Core";
import Footer from "@/components/footer/Footer";

export default function Home() {
    return (
        <>
            <Head>
                <title>IRDSM AVIATION v2 | Dashboard Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="app-admin-wrap layout-sidebar-compact sidenav-open clearfix sidebar-gradient-black-blue clearfix">
                {/*=============== Left side Start ================*/}

                <Navigation />

                {/*=============== Left side End ================*/}

                <div className="main-content-wrap d-flex flex-column">
                    {/*=============== Header Start ================*/}
                    <StatusBar />
                    {/*=============== Header End ================*/}

                    {/* ============ Body content start ============= */}
                    <div className="main-content">
                        <Breadscrumbs />

                        <Core />

                        {/* end of main-content */}
                        {/* Footer Start */}
                        <Footer />
                        {/* fotter end */}
                    </div>
                </div>
            </div>
            <Script
                src="js/plugins/jquery-3.3.1.min.js"
                onLoad={() => {
                    console.log("jquery has loaded");
                }}
                onError={() => {
                    console.error("jquery failed to load");
                }}
            />

            <Script
                src="js/plugins/bootstrap.bundle.min.js"
                onLoad={() => {
                    console.log("bootstrap has loaded");
                }}
                onError={() => {
                    console.error("bootstrap failed to load");
                }}
            />
            <Script
                src="js/plugins/perfect-scrollbar.min.js"
                onLoad={() => {
                    console.log("perfect-scrollbar has loaded");
                }}
                onError={() => {
                    console.error("perfect-scrollbar failed to load");
                }}
            />
            <Script
                src="js/scripts/script.min.js"
                onLoad={() => {
                    console.log("script min has loaded");
                }}
                onError={() => {
                    console.error("script min failed to load");
                }}
            />
            <Script
                src="js/scripts/sidebar.compact.script.min.js"
                onLoad={() => {
                    console.log("sidebar.compact.script has loaded");
                }}
                onError={() => {
                    console.error("sidebar.compact.script failed to load");
                }}
            />
            <Script
                src="js/scripts/customizer.script.min.js"
                onLoad={() => {
                    console.log("customizer script has loaded");
                }}
                onError={() => {
                    console.error("customizer script failed to load");
                }}
            />
            <Script
                src="js/plugins/echarts.min.js"
                onLoad={() => {
                    console.log("echarts has loaded");
                }}
                onError={() => {
                    console.error("echarts failed to load");
                }}
            />
            <Script
                src="js/scripts/echart.options.min.js"
                onLoad={() => {
                    console.log("echart.options has loaded");
                }}
                onError={() => {
                    console.error("echart.options failed to load");
                }}
            />
            <Script
                src="js/scripts/dashboard.v1.script.min.js"
                onLoad={() => {
                    console.log("dashboard.v1.script has loaded");
                }}
                onError={() => {
                    console.error("dashboard.v1.script failed to load");
                }}
            />
        </>
    );
}
